# /home/testuser/Linux-Infrastructure-Automation-Lab/ml_app-k8s-manifests/base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-deployment
  labels:
    app: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app
        image: dimitris424/ml-app:latest
        ports:
        - containerPort: 8000
        env:
        # Instead of a hardcoded value, we reference a secret
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-api-key-secret # The name of the Kubernetes Secret
              key: api-key # The key within the secret that holds the value
